###
Get http://localhost:4004/sales-order-srv/Items

###
Get http://localhost:4004/sales-order-srv/UnitOfMeasure

### Get Header
Get http://localhost:4004/sales-order-srv/Header

###
get https://localhost:4004/sales-order-srv/Header(ID='69ec0821-9810-41fa-b73b-d8620267e3eb')

###
POST https://localhost:4004/sales-order-srv/$batch HTTP/1.1
Content-Type: application/json

{
    "ID":"390cd79f-8c41-40d4-a567-5785d6cb0d07",
    "IsActiveEntity":"false"
}

###Create header
POST http://localhost:4004/sales-order-srv/Header HTTP/1.1
Content-Type: application/json

{
    "ID" : "b5fa3adb-097f-4a52-9c75-3100676677ff",
    "Email" : "head03@gmail.com",
    "FirstName": "Julio",
    "LastName" : "Tello",
    "Country": "PE",
    "CreateOn": "2023-03-28",
    "DeliveryDate": "2023-03-30T12:00:00Z",
    "OrderStatus": 1,
    "ImageUrl": "head003"  
}

### Get Header 2
Get http://localhost:4004/sales-order-srv/Header

### Update Sales
PUT http://localhost:4004/sales-order-srv/Header(b5fa3adb-097f-4a52-9c75-3100676677ff) HTTP/1.1
Content-Type: application/json

{
    "Email" : "",
    "FirstName" : "Juan",
    "LastName" : "Perez",
    "Country" : "PR",
    "DeliveryDate" : "2023-03-31T12:00:00Z",
    "OrderStatus" : 0,
    "CreateOn": "2023-04-10"
}


### Delete entity
DELETE http://localhost:4004/sales-order-srv/Header(b5fa3adb-097f-4a52-9c75-3100676677ff)

### Delete mediante acción
DELETE http://localhost:4004/sales-order-srv/Header('header01')/SalesOrderSrv.deleteOrder